//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveDetailManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class Employee
    {
        public int Id { get; set; }
        public string EmployeeName { get; set; }
        public int RoleID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string MailId { get; set; }
        public string PhoneNumber { get; set; }

       
    }
}
