//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveDetailManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public  class LeavesManagementDBEntities1 : DbContext
    {
        public LeavesManagementDBEntities1()
            : base("name=LeavesManagementDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<LeavesManagementDBEntities1>().ToTable("leavedetail");
        }
      
        public virtual DbSet<leavedetail> Leavedetails { get; set; }

        
       
    }
}
