//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveDetailManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public  class leavedetail
    {
        [Key]
        public int empid { get; set; }
        [Required]
        public string empname { get; set; }
        [DataType(DataType.DateTime)][Required]
        public System.DateTime FromDate { get; set; }
        [DataType(DataType.DateTime)]
        [Required]
        public System.DateTime ToDate { get; set; }
        public string Leavetype { get; set; }
        public string Descr { get; set; }
        public string status { get; set; }
       
       
    }
    public  class Status
    {
        public int StatusId { get; set; }
        public string StatusType { get; set; }
    }
}
